title: 혁신적인 개발자를 꿈꾸는 대학생
author: Junseok Oh
email: ohjunseok3089@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  아직 대학생입니다..
show_excerpts: true # set to true to show excerpts on the homepage
permalink: /:title
url: "https://ohjunseok3089.github.io"

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Junseok Oh
  tagline: 개발자를 꿈꾸는 대학생
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: true # set to true to add dark mode toggle
  disqus_shortname: ohjunseok3089

  # generate social links in footer
  social_links:
    github:  ohjunseok3089
    instagram: junseok._.o
    # linkedIn: in/fuzzysound
    rss: rss
    # twitter: 
    # dribbble: jekyll
    # flickr:   jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # facebook: jekyll
    # soundcloud: jekyll
    # telegram: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
remote_theme: thelehhman/plainwhite-jekyll

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

google_fonts: "Nanum+Gothic:400,700"